// biome-ignore lint/correctness/noUnusedImports: Required for JSX
import { Html } from "@elysiajs/html";

export function ChannelPoints() {
  return (
    <main class="w-full min-h-screen flex flex-col gap-6 px-2 lg:px-6 py-12">
      <div class="flex flex-row justify-between items-center">
        <h1 class="text-4xl font-bold">Channel Points Manager</h1>
        <button
          type="button"
          class="btn btn-success"
          id="addReward"
          onclick="rewardsDialog.showModal()"
        >
          Add Rewards
        </button>
      </div>
      <div class="min-h-screen bg-base-300 rounded-xl">
        <table class="table table-zebra w-full">
          <thead>
            <tr>
              <th>Toggle</th>
              <th>Name</th>
              <th>Cost</th>
              <th>Description</th>
              <th>Cooldown (s)</th>
              <th>Sound</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id="points-list"></tbody>
        </table>
      </div>

      <dialog id="rewardsDialog" class="modal">
        <div class="modal-box">
          <h3 class="text-lg font-bold">Reward</h3>
          <form id="rewardsForm" class="p-4 flex flex-col gap-6 w-full">
            <div class="flex flex-col gap-2">
              <fieldset class="fieldset">
                <legend class="fieldset-legend">Reward name:</legend>
                <input
                  type="text"
                  id="rewardName"
                  class="input w-full"
                  required
                />
              </fieldset>
              <fieldset class="fieldset">
                <legend class="fieldset-legend">Cost:</legend>
                <input
                  type="number"
                  id="rewardCost"
                  class="input w-full"
                  min="0"
                  value="100"
                />
              </fieldset>
              <fieldset class="fieldset">
                <legend class="fieldset-legend">Description:</legend>
                <input
                  type="text"
                  id="rewardDescription"
                  class="input w-full"
                  value="Redeem to trigger a sound | Generated by Manao"
                />
              </fieldset>
              <fieldset class="fieldset">
                <legend class="fieldset-legend">Cooldown (s):</legend>
                <input
                  type="number"
                  id="rewardCooldown"
                  class="input w-full"
                  min="0"
                  value="0"
                />
              </fieldset>

              <fieldset class="fieldset">
                <legend class="fieldset-legend">Sound:</legend>
                <select class="select select-bordered w-full" id="soundSelect">
                  <option disabled selected>
                    Select a sound
                  </option>
                </select>
              </fieldset>
            </div>
            <div class="flex flex-row w-full gap-2 justify-end items-center">
              <button type="button" class="btn btn-success" id="saveReward">
                Save
              </button>
              <button type="button" class="btn" onclick="rewardsDialog.close()">
                Close
              </button>
            </div>
          </form>
        </div>
      </dialog>
    </main>
  );
}
